### ISSUE TITLE
'p-checkbox' is not a known element

### ISSUE THREAD

**Issue by harvanchik** [miladfm/ngx-pretty-checkbox#7]
My Component's HTML
![Component HTML](https://user-images.githubusercontent.com/66141166/113795535-02f0db00-9702-11eb-9524-94b95e51cb7c.png)

My app.moudle.ts
![app,module.ts](https://user-images.githubusercontent.com/66141166/113795650-3e8ba500-9702-11eb-8747-8bba7aa947f8.png)

**Comment by miladfm** [comment]
Hi,

Which Version of Angular do yo have?

The Error is just in vscode or  'ng serve' has the same Error?

**Comment by harvanchik** [comment]
Using Angular 11.

I only see the error in VSCode.  There's no error in the console, and it appears to work in the browser.

**Comment by harvanchik** [comment]
Oh, so weird!  It randomly just went away.  I swear, I reloaded VSCode and restarted the server many times, but no luck.  But, I just looked back and it's not throwing an error anymore.  Very strange!

**Comment by miladfm** [comment]
New version of **Angular Language Service** extension work with AOT and Ivy but unfortunately right now it has many bugs and experimental features.

I have many same Problem with other Plugins and my local component too.
