### ISSUE TITLE
Angular 13 compatibilty

### ISSUE THREAD

**Issue by Nickael** [miladfm/ngx-pretty-checkbox#9]
Hi, I was testing you lib on my local project before deploying on prod, and because i'm on Angular 13, I can't use you lib without forking it.
Is there a possibility that the angular compatibility may be updated ?

Regards

**Comment by miladfm** [comment]
Hi, sure I will update it by the end of this week

**Comment by dJani97** [comment]
@miladfm Hi!

Could you please publish this update anytime soon? Angular 14 support would also be welcome. 

May I assist in some way?

**Comment by miladfm** [comment]
Sure, sorry, I was busy with other projects and I forgot about this issue.
I can upgrade the library to angular 14 at weekend, but if you need immediately the update, you can send me a PR and I will check it and merge it soon.

**Comment by dJani97** [comment]
Take your time, we've already implemented custom checkboxes with CSS.
